
Booting from Hard Disk...
Boot failed: could not read the boot disk

Booting from Floppy...
Loading EPOS .... done
Ignoring ELF segment 1 at 0x80480d4!

*** This is EPOS!

Setting up this machine as follows: 
  Mode:         library
  Processor:    1 x IA32 at 2000 MHz (BUS clock = 2000 MHz)
  Machine:      PC
  Memory:       1048576 KB [0x00000000:0x40000000]
  User memory:  1047472 KB [0x00000000:0x3feec000]
  I/O space:    28612 KB [0xfd000000:0xfebf1000]
  Node Id:      will get from the network!
  Position:     will get from the network!
  Setup:        20256 bytes
  APP code:     45056 bytes     data: 4214784 bytes

CPU 0 Fila 0 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 1 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 2 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 3 Tamanho  0 CPU 0 CHOSEN: 0xffc3fe14

CPU 0 Fila 0 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 1 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 2 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 3 Tamanho  1 0xffc3bc50 CPU 0 CHOSEN: 0xffc3fe14

MAIN: Hello world!
CPU 0 Fila 0 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 1 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 2 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 3 Tamanho  1 0xffc3bc50 CPU 0 CHOSEN: 0xffc3fe14

Thread::resume(this=0x80800e28) state= 2
Calling handle
RESUME_THREAD called, is periodic
EET restante: 19080
RP waiting time: 0
CWT: 0, Time to run: 120000, IDLE time: 100920
Thread inserted in queue 3 with priority 0


Calling resume
Calling reschedule
JOB RELEASE
EET restante: 19080
RP waiting time: 0
Pulando uma thread aperiodica
Thread não cabe na fila 3
EET restante: 15960
RP waiting time: 20000
CWT: 20000, Time to run: 100000, IDLE time: 84040
Thread inserted in queue 2 with priority 20000


ENTER !!
CPU 0 Fila 0 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 1 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 2 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 3 Tamanho  1 0xffc3bc50 CPU 0 CHOSEN: 0x80800e28

JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB FINISH
JOB RELEASE
EET restante: 19080
RP waiting time: 0
CWT: 0, Time to run: 120000, IDLE time: 100920
Thread inserted in queue 3 with priority 0


JOB FINISH
ENTER !!
CPU 0 Fila 0 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 1 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 2 Tamanho  0 CPU 0 CHOSEN: 0x00000000
CPU 0 Fila 3 Tamanho  1 0xffc3bc50 CPU 0 CHOSEN: 0x00000000

IC::exc_gpf(cs=0,ip=0x00000000,fl=0)

PANIC: unexpected error!
Rebooting the machine!
make[2]: Leaving directory '/app/img'
make[1]: Leaving directory '/app'